apiVersion: core.openfunction.io/v1alpha1
kind: Function
metadata:
  name: autoscaling-producer
spec:
  version: "v1.0.0"
  image: openfunctiondev/autoscaling-producer:v0.3.1
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/go115-builder:v0.2.2
    env:
      FUNC_NAME: "Producer"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "v0.3.1/functions/OpenFuncAsync/pubsub/producer/"
  serving:
    template:
      containers:
        - name: function
          imagePullPolicy: Always
    runtime: "OpenFuncAsync"
    params:
      PUBSUB_NAME: autoscaling-producer
      TOPIC_NAME: metric
      NUMBER_OF_PUBLISHERS: "2"
      PUBLISHERS_FREQ: "100ms"
      PUBLISHERS_DELAY: "10s"
      LOG_FREQ: "3s"
      PUBLISH_TO_CONSOLE: "false"
    openFuncAsync:
      dapr:
        outputs:
          - name: autoscaling-producer
            type: pubsub
            topic: metric
        annotations:
          "dapr.io/log-level": "debug"
        components:
          - name: autoscaling-producer
            type: pubsub.kafka
            version: v1
            metadata:
              - name: brokers
                value: "kafka-pubsub-server-kafka-brokers:9092"
              - name: authRequired
                value: "false"
              - name: allowedTopics
                value: "metric"
              - name: consumerID
                value: "autoscaling-producer"

