apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub # midlleware component name
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: ${YOUR_REDIS_ADDRESS}
  - name: redisPassword
    value: ""