apiVersion: core.openfunction.io/v1alpha1
kind: Function
metadata:
  name: bindings-without-output
spec:
  version: "v1.0.0"
  image: openfunctiondev/bindings-without-output:v0.3
  imageCredentials:
    name: push-secret
  build:
    builder: "openfunction/builder-go:v0.2.2-1.15"
    env:
      FUNC_NAME: "BindingsNoOutput"
    srcRepo:
      revision: "release-0.3"
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/OpenFuncAsync/bindings/without-output/"
  serving:
    template:
      containers:
        - name: function
          imagePullPolicy: Always
    runtime: "OpenFuncAsync"
    openFuncAsync:
      dapr:
        inputs:
          - name: cron
            type: bindings
        annotations:
          "dapr.io/log-level": "debug"
        components:
        - name: cron
          type: bindings.cron
          version: v1
          metadata:
          - name: schedule
            value: "@every 2s"
