apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
  name: bindings-without-output
spec:
  version: "v1.0.0"
  image: openfunctiondev/bindings-without-output:v0.5.0
  imageCredentials:
    name: push-secret
  build:
    builder: "openfunction/builder-go:v0.4.0-1.15"
    env:
      FUNC_NAME: "BindingsNoOutput"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "v0.5.0/functions/OpenFuncAsync/bindings/without-output/"
  serving:
    runtime: "OpenFuncAsync"
    openFuncAsync:
      dapr:
        inputs:
          - name: cron
            component: cron
            type: bindings
        annotations:
          "dapr.io/log-level": "debug"
        components:
          cron:
            type: bindings.cron
            version: v1
            metadata:
              - name: schedule
                value: "@every 2s"

