apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: logs-sync-handler
spec:
  version: "v2.0.0"
  image: openfunctiondev/logs-sync-handler:v2
  imageCredentials:
    name: push-secret
  build:
    builder: openfunction/builder-go:v2-1.16
    env:
      FUNC_NAME: "LogsHandler"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/knative/logs-handler-function/"
      revision: "release-0.6"
  serving:
    runtime: "knative"
    template:
      containers:
        - name: function
          imagePullPolicy: IfNotPresent
