apiVersion: core.openfunction.io/v1alpha1
kind: Function
metadata:
  name: logs-sync-handler
spec:
  version: "v1.0.0"
  image: openfunctiondev/logs-sync-handler:v1
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/go115-builder:v0.2.0
    env:
      FUNC_NAME: "LogsHandler"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/Knative/logs-handler-function/"
  serving:
    runtime: "Knative"