apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
  name: logs-sync-handler
spec:
  version: "v1.0.0"
  image: openfunctiondev/logs-sync-handler:latest
  imageCredentials:
    name: push-secret
  build:
    builder: openfunction/builder-go:v0.4.0-1.15
    env:
      FUNC_NAME: "LogsHandler"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/Knative/logs-handler-function/"
  serving:
    runtime: "Knative"
    template:
      containers:
        - name: function
          imagePullPolicy: Always
