apiVersion: core.openfunction.io/v1alpha2
kind: Function
metadata:
  name: logs-sync-handler
spec:
  version: "v1.0.0"
  image: openfunctiondev/logs-sync-handler:latest
  imageCredentials:
    name: push-secret
  build:
    builder: openfunctiondev/go115-builder:v0.3.0
    env:
      FUNC_NAME: "LogsHandler"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "latest/functions/Knative/logs-handler-function/"
  serving:
    runtime: "Knative"
    template:
      containers:
        - name: function
          imagePullPolicy: Always
