apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: bindings-without-output
spec:
  version: "v2.0.0"
  image: openfunctiondev/bindings-without-output:v2
  imageCredentials:
    name: push-secret
  build:
    builder: openfunction/builder-go:v2-1.16
    env:
      FUNC_NAME: "BindingsNoOutput"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/Async/bindings/without-output"
      revision: "release-0.6"
  serving:
    template:
      containers:
        - name: function
          imagePullPolicy: IfNotPresent
    runtime: "async"
    inputs:
      - name: input
        component: cron
    bindings:
      cron:
        type: bindings.cron
        version: v1
        metadata:
        - name: schedule
          value: "@every 2s"
