apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: output-target
spec:
  version: "v2.0.0"
  image: openfunctiondev/bindings-output-target:v2
  imageCredentials:
    name: push-secret
  build:
    builder: openfunction/builder-go:v2-1.16
    env:
      FUNC_NAME: "Target"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "functions/Async/bindings/with-output/output-target"
      revision: "release-0.6"
  serving:
    runtime: async
    inputs:
      - name: greeting
        component: target-topic
    bindings:
      target-topic:
        type: bindings.kafka
        version: v1
        metadata:
          - name: brokers
            value: "kafka-server-kafka-brokers:9092"
          - name: topics
            value: "sample-topic"
          - name: consumerGroup
            value: "output-target"
          - name: publishTopic
            value: "sample-topic"
          - name: authRequired
            value: "false"
    template:
      containers:
        - name: function
          imagePullPolicy: IfNotPresent
