apiVersion: core.openfunction.io/v1alpha1
kind: Function
metadata:
  name: bindings-with-output
spec:
  version: "v1.0.0"
  image: openfunctiondev/bindings-with-output:v0.3.1
  imageCredentials:
    name: push-secret
  build:
    builder: "openfunctiondev/go115-builder:v0.2.2"
    env:
      FUNC_NAME: "BindingsOutput"
    srcRepo:
      url: "https://github.com/OpenFunction/samples.git"
      sourceSubPath: "v0.3.1/functions/OpenFuncAsync/bindings/with-output/"
  serving:
    template:
      containers:
        - name: function
          imagePullPolicy: Always
    runtime: "OpenFuncAsync"
    openFuncAsync:
      dapr:
        inputs:
          - name: cron
            type: bindings
        outputs:
          - name: sample-topic
            type: bindings
            params:
              operation: "create"
              type: "bindings"
        annotations:
          "dapr.io/log-level": "debug"
        components:
        - name: cron
          type: bindings.cron
          version: v1
          metadata:
          - name: schedule
            value: "@every 2s"
        - name: sample-topic
          type: bindings.kafka
          version: v1
          metadata:
          - name: brokers
            value: "kafka-bindings-server-kafka-brokers:9092"
          - name: topics
            value: sample
          - name: consumerGroup
            value: group1
          - name: publishTopic
            value: sample
          - name: authRequired
            value: "false"
